### PR TITLE
Feature/params convention

### PR DESCRIPTION
**Pull request by aragon999**
Very nice parameter convention :-)

But I think (for the development experience), it would be much better if the `nargs` parameter would be optional and automatically computed.
I still left the possibility to set it manually.

I included the QCD fermion operators test into the test matrix, where I created a random field if the configuration used is not present (as for the CI).
This can probably also be done for the other tests, I have not looked into that, but this would then resolve: 
https://github.com/lehner/gpt/issues/9

Furthermore I reformatted some code with `black`. Let me know what you think or what should be changed, or if we should only apply some changes.

### CODE REVIEW

**Comment by lehner** [comment]
Thanks!

Let us deal with the style questions separately.  I am happy to pull all other three commits.  Do you
want to update your PR?

**Comment by aragon999** [comment]
Okay, yes I will update the commit to just fix the indentation to 4 spaces in params.py

**Comment by aragon999** [comment]
I updated the commits and removed all code style changes.

**Comment by lehner** [comment]
Thank you. I am finishing up some other added features and will merge this after that later this week.

**Pull request merged**
