### PR TITLE
Hadron2pt routines (quark contraction routines + Light-Strange-Heavy spectrum), Nucleon3pt sequential sources, Spin Matrices, Wuppertal quark smearing, Ape-link smearing, Polyakov loop

### PR DESCRIPTION
**Pull request by Lorenzo-Barca**
Added routines for mesons2pt, meson3pt with specific momentum projection and spin matrices

### CODE REVIEW

**Comment by lehner** [comment]
Dear Lorenzo, it looks like you added the .o files to the git repository.  Please kindly remove them from the version history.  (git rm)  Thanks!

**Comment by lehner** [comment]
Also all the out and err files need to be removed.  Thanks!

**Comment by Lorenzo-Barca** [comment]
Dear Christoph,

Thanks for the response!
I hope that the issues are now solved and 
Sorry for the several commitments.
I have added "*.o" in .gitignore. Would that be a problem?

(and I manually deleted the log directory in gpt/lib/cgpt/" before committing)

Tasks accomplished
I have also added :
- routine for a meson2pt with different momentum projections in 'gpt/test/qcd' 
;
- routine for a meson3pt with different momentum projections at the sink in
'gpt/test/qcd/' ;
- routine with matrices, useful e.g. for the hadron spectrum ;
- quark contractions routines in 'gpt/lib/gpt/core' + test contractions routine
in 'gpt/test/qcd' ;


Next tasks
- baryon2pt routine ; ( almost done) 
- baryon3pt routine ; ( almost done )
- Wuppertal quark smearing ; ( almost done )
- Momentum quark smearing ;


Comments
- I am not happy with the performance of the quark contractions routines.
  I will do a comparison with Chroma using its libraries "quarkContractXY"


- I get odd errors when I multiply on the right a lattice object by a gamma
matrix.
  (I need a right multiplication for the baryon spectrum as well)


Thanks a lot.


Best Regards,
Lorenzo 


>>> Christoph Lehner <notifications@github.com> 08/11/20 12:38 PM >>>

 Dear Lorenzo, it looks like you added the .o files to the git repository. 
Please kindly remove them from the version history.  (git rm)  Thanks!

**Comment by lehner** [comment]
Hi Lorenzo, the .o files are still part of the repository, could you remove them as well?  They should not be included with git add .  The "Files changed" tab here provides a nice overview with what you added (143 files currently) and I think you only wanted to add O(4) ?  I will look in more detail at the rest later.  Thanks!

**Comment by lehner** [comment]
Hi Lorentzo,

thanks for cleaning up and for your work!  A few more points:

1. All of this infrastructure is QCD/Gauge-theory-specific and should be moved outside of core and into "qcd".

2. We need to discuss the naming schemes to be more in line with the rest of the code.

3. The mathematical expressions motivating the individual quark contraction needs to be added as a comment.
   Look, e.g., into lib/gpt/algorithms/inverter/defect_correcting.py .

4. The role of the provided tests is not clear.  The 2pt and 3pt tests do not seem to check anything that was not
   checked before in the current test suit.  They probably should be moved to the applications directory and made
   part of a standard measurement package.   The more specific tests are incomplete (do not test all functions)
   and should be performed using properties of the functions instead of repeating the code.

We should discuss these points in the next GPT meeting to make a work plan.  (I, e.g., could deal with the
naming/infrastructure questions, but it would be great if we first discuss the tests and you could work on those.)

Cheers,

  Christoph

**Comment by lehner** [comment]
In addition to the last comments, the code is Nc=3 specific.  The code would likely be more elegant and reusable if we introduced the concept of epsilon tensors and wrote this out as general tensor contractions.  Your current code could then serve as a test for the Nc=3 case.  Let us also discuss this in the next meeting.

**Comment by Lorenzo-Barca** [comment]
Dear Christoph,

I completely agree with all the points you are mentioning 
and I wanted to discuss those in detail in the next GPT meeting.

Cheers,
Lorenzo

**Comment by Lorenzo-Barca** [comment]
Dear Christoph, the routines work fine and they are ready for your review. 
In particular, we should discuss:
- how to handle with the h5py library to pass the tests;
- do we want a parameter list to read as an input file? 
  This way, we could store the parameters into the hdf5 and make the simulation reproducible;
- modularity of the baryon code;
- test routines for coverage.

When you have time we can finalize this. Thanks a lot.
Cheers,
Lorenzo

**Pull request closed without merging**
