### PR TITLE
Tune Coulomb gauge fixing

### PR DESCRIPTION
**Pull request by waterret**
Did some tuning for the coulomb gauge fixing to make it more stable. The original version occasionally returns NaN.

### CODE REVIEW

**Comment by lehner** [comment]
Hi Luchang,

thanks for pointing out these issues with occasional NaNs in the original gauge fixing/non_linear_cg code.  I was able to reproduce the problem and agree with the need for improvements.  I prefer, however, a somewhat more minimal approach.  

There were two issues as far as I can see:

1. The g.matrix.exp was not precise enough in some cases, which lead to a substantial departure from the SU(3) manifold.  I was able to fix this by just adjusting the max_n parameter, which was supposed to capture this but was not chosen sufficiently conservative.
2. The line search occasionally suggests a very large step size, likely because the function locally is not close to a quadratic function anymore.  This, however, can be fixed simply by introducing a maximal step size, which also triggers a restart of the non-linear cg.

Please have a look at the recent commit c94755a7aa187d1e859bb5909afe9ae45d8a0f62, which implements this.

I would close this pull request for now and hope that you find the issue also sufficiently addressed with this more minimal approach.

Thanks again!

-- Christoph

**Comment by lehner** [comment]
For completeness: I was able to reproduce the original problem on the 24ID ensembles, while everything was stable on my original tests on the 96I.  Now both are stable.

**Comment by waterret** [comment]
Hi Christoph,

Thank you for the correspondence. The changes I made was messy partly due to I didn't know the cause of the NaN problem. Therefore, I made a lot of defensive changes to track down the issue, some of them were not nessesary but I didn't remove. Now, we have better understanding of the source of the problem. I think your new commit is a cleaner way to solve the problem. I will also do some more tests with your new commit. Thanks!

-- Luchang

**Comment by waterret** [comment]
I have tested your commit with both 24I and 48I configurations and it worked well. Nice.

**Pull request closed without merging**
