### PR TITLE
Missing sitewise inversions

### PR DESCRIPTION
**Pull request by DanielRichtmann**

### CODE REVIEW

**Comment by lehner** [comment]
There are opportunities for code reuse that I would like to consider before pulling this.  There should be only one invertMatrix and one determinant function and the template specialization should be on the level of converting (a vector of) scalar objects to Eigen matrices and back.  The we also get all determinant functions for free and have infrastructure for future extensions: eigenvectors, matrix exponentials using eigen etc.

**Comment by DanielRichtmann** [comment]
If I understood you correctly, you had something like this in mind (the code still needs some cleaning). Atm the matrix with virtual fields is still in a separate function but if we agree on the general strategy, I would now integrate this, too.

**Comment by lehner** [comment]
Yes, this looks very close to what I thought.  Final small tuning I will do myself.  Thanks!

**Comment by lehner** [comment]
My small tuning turned out to involve a few changes which you can find mostly here:

https://github.com/lehner/gpt/blob/master/lib/cgpt/lib/foundation/eigen.h

and

https://github.com/lehner/gpt/blob/master/lib/cgpt/lib/foundation/matrix.h .

Most importantly, adding new functions (exp, log, cos, sin, ...) now only should take a few
more lines.

**Pull request merged**
