### PR TITLE
Feature/test help message

### PR DESCRIPTION
**Pull request by aragon999**
I included a test of the help message in the test-`run` script.
Is it fine in this way, or do we want to check some output? 

I also improved the handling when calling the `--help` with more than one rank, I needed to use the MPI variables set by the MPI wrapper, since MPI is not initialized at that point. Not sure if this is the best way to handle this.

### CODE REVIEW

**Comment by lehner** [comment]
Thanks!  Checking MPI-version-specific environment variables should be avoided.  The root cause
should be addressed, i.e., the flags should be evaluated only after MPI is initialized:

So a better way to handle this is to move the parsing of the help out of the initialization of the 
default submodule and into a function default.parse_args()
that gets called after cgpt.init.  For this to work, however, we need to remove the "--help" 
from sys.argv before calling cgpt.init since Grid otherwise exits at this point.

I would close the current version but would be happy to consider an implementation that follows the above outline.  (I may also attempt to do this if I have some time.)

**Comment by lehner** [comment]
Max, I have this almost ready, let me implement the proper treatment of "--help" and then I will merge your addition to the tests.

**Comment by lehner** [comment]
Yes, rebasing would be great.  The commit

https://github.com/lehner/gpt/commit/89137622507e8b2ab6c58150f2c59359c9a20ce3

should fix the help problem.

**Comment by lehner** [comment]
Thanks, sorry to do this but I have also suggestions for the one line change :)

In many of my setups the runner is not python, but your modification assumes that it
knows how to interpret -m gpt .

I will make a counter proposal.

**Comment by aragon999** [comment]
All good. I am happy to discuss changes and prefer more robust solutions :-)

**Pull request merged**
