### PR TITLE
Feature/CI

### PR DESCRIPTION
**Pull request by pjgeorg**
Add CI actions: running on github runners and actions to trigger RQCD GitLab CI (currently does nothing).
- CI running on github runners. Builds gpt with all dependencies and runs gpt tests. It is triggered on any push and pull request to build gpt. Current Test matrix: Python: 3.6, 3.7, 3.8; Compiler: gcc, clang; MPI: none, MPICH, OpenMPI
- Action to trigger RQCD CI. RQCD CI currently does nothing. It is only triggered on push to master. Maybe change to devel (once a devel exists) later. Requires to add secrets: RQCD_CA_BUNDLE and RQCD_TRIGGER_TOKEN

PR is based on / includes:
- Stefan's PR #13 + PR to his branch (https://github.com/ssolbUR/gpt/pull/2)
- CI work has mainly been done by Max (PR #12 ), this series is based on his work.

Please comment/discuss so we can agree whether this is the way we want to integrate CI or changes are required.

PS: Ignore results of the Actions in my fork, this is due to outdated Action caches. Haven't found a way to delete these. However, even ignoring these caches all test pipelines currently fail. Compilation works fine.

### CODE REVIEW

**Comment by pjgeorg** [comment]
After last commit all caches have been re-created, you can check the output of all tests here: https://github.com/pjgeorg/gpt/actions/runs/122427906

**Comment by lehner** [comment]
@pjgeorg Can you confirm that this is now ready to be pulled from your end?

**Comment by pjgeorg** [comment]
In my opinion it is ready to be pulled.

**Comment by pjgeorg** [comment]
@lehner I will send you the required RQCD_CA_BUNDLE and RQCD_TRIGGER_TOKEN via mail.

**Pull request merged**
